name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mamba
  - ipykernel
  - ipympl
  - ipywidgets
  - xarray
  - netcdf4
  - matplotlib
  - numpy
  - eomaps
  - scipy
  - ca-certificates
  - certifi
  - openssl
  - eodag
